[package]
name = "flock"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
criterion = { workspace = true }
flock-prover = { git = "https://github.com/succinctlabs/flock", rev = "4af7a4da3b60f2ac86ab9aaf2c6a4ff1de416b3a" }
serde = { workspace = true }
utils = { workspace = true }

[[bench]]
name = "sha256"
harness = false

[[bench]]
name = "blake3"
harness = false

[[bench]]
name = "keccak"
harness = false

[[bin]]
name = "sha256_mem_flock"
path = "src/bin/sha256_mem.rs"

[[bin]]
name = "blake3_mem_flock"
path = "src/bin/blake3_mem.rs"

[[bin]]
name = "keccak_mem_flock"
path = "src/bin/keccak_mem.rs"
