[package]
name = "stark-v-bench-blake3"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = { version = "1.8", default-features = false }
guest-bin = { git = "https://github.com/ClementWalter/stark-v", rev = "0bf633bc5a87b14d2e2ad4d8f30be2701849e0c1" }
guest-lib = { git = "https://github.com/ClementWalter/stark-v", rev = "0bf633bc5a87b14d2e2ad4d8f30be2701849e0c1" }

[workspace]
