name: "Install Nargo"
description: "Installs the noir-lang toolchain"

inputs:
  version:
    description: Version of Nargo/Noir binaries.
    required: false
    default: "1.0.0-beta.19"

runs:
  using: "composite"
  steps:
    - name: Install Nargo
      uses: noir-lang/noirup@v0.1.4
      with:
        toolchain: ${{ inputs.version }}
