name: "Install Nargo"
description: "Installs the noir-lang toolchain"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash
        source ~/.bashrc
        ~/.nargo/bin/noirup --version 1.0.0-beta.9
