[package]
name = "stark-v-bench-keccak"
version = "0.1.0"
edition = "2021"

[dependencies]
guest-bin = { git = "https://github.com/AntoineFONDEUR/stark-v", rev = "740812dfb29bfd05e24c9e8b1ad6b211ac1b564e" }
guest-lib = { git = "https://github.com/AntoineFONDEUR/stark-v", rev = "740812dfb29bfd05e24c9e8b1ad6b211ac1b564e" }
sha3 = { version = "0.10", default-features = false }

[workspace]
