[package]
name = "stark-v"
version = "0.1.0"
edition = "2021"

[dependencies]
stark-v-sdk = { git = "https://github.com/ClementWalter/stark-v", rev = "0bf633bc5a87b14d2e2ad4d8f30be2701849e0c1" }
ere-zkvm-interface = { git = "https://github.com/eth-act/ere", rev = "66c516a24d9c3549f76b84f72365ab544299e63a" }
bincode = "1.3"
clap = { version = "4.5", features = ["derive", "env"] }
utils = { path = "../utils" }

[dev-dependencies]
criterion = "0.5"

[features]
default = ["parallel"]
parallel = ["stark-v-sdk/parallel"]

[[bench]]
name = "sha256"
harness = false

[[bench]]
name = "keccak"
harness = false

[[bench]]
name = "private_tx"
harness = false

[[bench]]
name = "constant_overhead"
harness = false

[[bench]]
name = "merkle_fake"
harness = false

[[bench]]
name = "hash_sha256"
harness = false

[[bench]]
name = "merkle_sha256"
harness = false

[[bench]]
name = "hash_keccak"
harness = false

[[bench]]
name = "merkle_keccak"
harness = false

[[bin]]
name = "sha256_mem_stark_v"
path = "src/bin/sha256_mem.rs"

[[bin]]
name = "keccak_mem_stark_v"
path = "src/bin/keccak_mem.rs"

[[bin]]
name = "private_tx_mem_stark_v"
path = "src/bin/private_tx_mem.rs"

[[bin]]
name = "constant_overhead_mem_stark_v"
path = "src/bin/constant_overhead_mem.rs"

[[bin]]
name = "merkle_fake_mem_stark_v"
path = "src/bin/merkle_fake_mem.rs"

[[bin]]
name = "hash_sha256_mem_stark_v"
path = "src/bin/hash_sha256_mem.rs"

[[bin]]
name = "merkle_sha256_mem_stark_v"
path = "src/bin/merkle_sha256_mem.rs"

[[bin]]
name = "hash_keccak_mem_stark_v"
path = "src/bin/hash_keccak_mem.rs"

[[bin]]
name = "merkle_keccak_mem_stark_v"
path = "src/bin/merkle_keccak_mem.rs"
