[package]
name = "jolt-keccak"
version = "0.1.0"
edition = "2021"

[dependencies]
ere-platform-jolt = { git = "https://github.com/eth-act/ere", rev = "9bf9772b50fbe74310259718129dc5b2b530524d", features = ["guest-std"] }
jolt-inlines-keccak256 = { git = "https://github.com/a16z/jolt", rev = "6dcd401" }

[features]
guest = []

[workspace]
