name: "Install SP1 toolchain"
description: "Installs the SP1 toolchain"
inputs:
  token:
    description: "GitHub token for SP1 authentication"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -L https://sp1up.succinct.xyz | bash
        source ~/.bashrc
        ~/.sp1/bin/sp1up -C v5.0.8 --token ${{ inputs.token }}
        ~/.sp1/bin/cargo-prove prove --version
