name: "Install SP1 toolchain"
description: "Installs the SP1 toolchain components required for benchmarks"

inputs:
  sp1-version:
    description: "SP1 toolchain version"
    required: false
    default: "v5.2.1"

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      run: |
        set -Eeuo pipefail

        if [[ ! -x "$HOME/.sp1/bin/sp1up" ]]; then
          curl -fsSL --retry 5 --proto '=https' --tlsv1.2 https://sp1up.succinct.xyz | bash
        fi

        export PATH="$HOME/.sp1/bin:$PATH"
        echo "$HOME/.sp1/bin" >> "$GITHUB_PATH"

        sp1up -v "${{ inputs.sp1-version }}" --token "$GITHUB_TOKEN"

        cargo-prove prove --version
