[package]
name = "leanvm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
utils = { workspace = true }

lean_backend = { package = "backend", git = "https://github.com/alxkzmn/leanVM.git", branch = "blake3-precompile" }
lean_compiler = { git = "https://github.com/alxkzmn/leanVM.git", branch = "blake3-precompile" }
lean_prover = { git = "https://github.com/alxkzmn/leanVM.git", branch = "blake3-precompile" }
lean_vm = { git = "https://github.com/alxkzmn/leanVM.git", branch = "blake3-precompile" }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "private_tx"
harness = false

[[bench]]
name = "constant_overhead"
harness = false

[[bench]]
name = "merkle_fake"
harness = false

[[bench]]
name = "hash_poseidon16"
harness = false

[[bench]]
name = "merkle_poseidon16"
harness = false

[[bench]]
name = "hash_blake3"
harness = false

[[bench]]
name = "merkle_blake3"
harness = false

[[bin]]
name = "private_tx_mem_leanvm"
path = "src/bin/private_tx_mem.rs"

[[bin]]
name = "constant_overhead_mem_leanvm"
path = "src/bin/constant_overhead_mem.rs"

[[bin]]
name = "merkle_fake_mem_leanvm"
path = "src/bin/merkle_fake_mem.rs"

[[bin]]
name = "hash_poseidon16_mem_leanvm"
path = "src/bin/hash_poseidon16_mem.rs"

[[bin]]
name = "merkle_poseidon16_mem_leanvm"
path = "src/bin/merkle_poseidon16_mem.rs"

[[bin]]
name = "hash_blake3_mem_leanvm"
path = "src/bin/hash_blake3_mem.rs"

[[bin]]
name = "merkle_blake3_mem_leanvm"
path = "src/bin/merkle_blake3_mem.rs"
