name: "Install RISC0 toolchain"
description: "Installs the RISC0 toolchain"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -L https://risczero.com/install | bash
        ~/.risc0/bin/rzup install rust 1.81.0
        ~/.risc0/bin/rzup install cpp 2024.1.5
        ~/.risc0/bin/rzup install r0vm 3.0.1
        ~/.risc0/bin/rzup install cargo-risczero 3.0.1
