name: "Install SP1 toolchain"
description: "Installs the SP1 toolchain"
runs:
  using: "composite"
  steps:
    - run: |
        curl -L https://sp1up.succinct.xyz | bash
        ~/.sp1/bin/sp1up 
        ~/.sp1/bin/cargo-prove prove --version
