
[workspace]

[package]
name = "jolt-mobile"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

# Adapters for different proof systems
[features]
default = ["uniffi"]
uniffi = ["mopro-ffi/uniffi"]
flutter = ["mopro-ffi/flutter"]
wasm = ["mopro-ffi/wasm"]

[dependencies]
mopro-ffi = { version = "=0.3.6" }
thiserror = "2.0.12"
anyhow = "1.0.99"
jolt-bench = { path = "../../jolt", package = "jolt" }
utils = { path = "../../utils" }
ere-jolt = { git = "https://github.com/eth-act/ere", rev = "6573843" }

# CIRCOM_DEPENDENCIES
# HALO2_DEPENDENCIES
# NOIR_DEPENDENCIES
# GNARK_DEPENDENCIES

[build-dependencies]
# CIRCOM_BUILD_DEPENDENCIES
# HALO2_BUILD_DEPENDENCIES
# NOIR_BUILD_DEPENDENCIES
# GNARK_BUILD_DEPENDENCIES

[dev-dependencies]
mopro-ffi = { version = "=0.3.6", features = ["uniffi-tests"] }

# CIRCOM_DEV_DEPENDENCIES
# HALO2_DEV_DEPENDENCIES
# NOIR_DEV_DEPENDENCIES
# GNARK_DEV_DEPENDENCIES

[target.wasm32-unknown-unknown.dependencies]
mopro-ffi = { version = "=0.3.6", features = ["wasm"] }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"

[patch.crates-io]
ark-ff = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-ec = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-serialize = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-bn254 = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
allocative = { git = "https://github.com/facebookexperimental/allocative", rev = "85b773d85d526d068ce94724ff7a7b81203fc95e" }
