
[workspace]

[package]
name = "jolt-mobile"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = ["uniffi"]
uniffi = ["mopro-ffi/uniffi"]
wasm = []

[dependencies]
mopro-ffi = { version = "=0.3.6" }
thiserror = "2.0.12"
jolt-bench = { path = "../../jolt", package = "jolt" }
utils = { path = "../../utils" }
ere-jolt = { git = "https://github.com/eth-act/ere", rev = "6573843" }

[patch.crates-io]
ark-ff = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-ec = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-serialize = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-bn254 = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
allocative = { git = "https://github.com/facebookexperimental/allocative", rev = "85b773d85d526d068ce94724ff7a7b81203fc95e" }
