name: "Install OpenMPI"
description: "Installs the OpenMPI library"

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
        HOMEBREW_NO_INSTALL_CLEANUP: "1"
        HOMEBREW_NO_ENV_HINTS: "1"
      run: |
        brew install open-mpi
        mpirun --version
        which mpicc
