name: "Install Barretenberg(bbup)"
description: "Installs the Barretenberg proving backend for noir-lang benchmarking"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/refs/heads/next/barretenberg/bbup/install | bash
        source ~/.bashrc
        bbup -v 0.87.0
        echo "$HOME/.bb" >> $GITHUB_PATH