name: "Install Barretenberg(bbup)"
description: "Installs the Barretenberg proving backend for noir-lang benchmarking"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/refs/heads/next/barretenberg/bbup/install | bash
        export PATH="$HOME/.bb:$PATH"
        bbup -v 5.0.0-nightly.20260324
        echo "$HOME/.bb" >> $GITHUB_PATH
