[package]
name = "jolt-ecdsa"
version = "0.1.0"
edition = "2021"

[dependencies]
ere-platform-jolt = { git = "https://github.com/eth-act/ere", rev = "9bf9772b50fbe74310259718129dc5b2b530524d", features = ["guest-std"] }
jolt-inlines-secp256k1 = { git = "https://github.com/a16z/jolt", rev = "6dcd401" }
postcard = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[features]
guest = []

[workspace]
