[package]
name = "jolt-sha256"
version = "0.1.0"
edition = "2021"

[dependencies]
ere-platform-jolt = { "https://github.com/alxkzmn/ere", default-features = false, features = ["guest-std"] }
jolt-inlines-sha2 = { git = "https://github.com/a16z/jolt", rev = "35d46f5" }

[features]
default = ["guest"]
guest = []

[workspace]
