[workspace]
members = [
    "ecdsa_p256",
    "keccak_lib",
    "keccak_128",
    "keccak_256",
    "keccak_512",
    "keccak_1024",
    "keccak_2048",
    "poseidon_2",
    "poseidon_4",
    "poseidon_8",
    "poseidon_12",
    "poseidon_16",
    "poseidon2_2",
    "poseidon2_4",
    "poseidon2_8",
    "poseidon2_12",
    "poseidon2_16",
    "sha256_128",
    "sha256_256",
    "sha256_512",
    "sha256_1024",
    "sha256_2048",
]
