name: "Install LLVM and LLD"
description: "Installs LLVM and LLD toolchain"

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
        HOMEBREW_NO_INSTALL_CLEANUP: "1"
        HOMEBREW_NO_ENV_HINTS: "1"
      run: |
        brew install llvm lld
        echo "CC=/opt/homebrew/opt/llvm/bin/clang" >> "$GITHUB_ENV"
        echo "CXX=/opt/homebrew/opt/llvm/bin/clang++" >> "$GITHUB_ENV"
        echo "AR=/opt/homebrew/opt/llvm/bin/llvm-ar" >> "$GITHUB_ENV"
        echo "RANLIB=/opt/homebrew/opt/llvm/bin/llvm-ranlib" >> "$GITHUB_ENV"
